// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ProxyAPI2.ApiModel;
//
//    var comment = Comment.FromJson(jsonString);

namespace ProxyAPI2.ApiModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Comment
    {
        [JsonProperty("postId")]
        public long PostId { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }

    public partial class Comment
    {
        public static List<Comment> FromJson(string json) => JsonConvert.DeserializeObject<List<Comment>>(json, ProxyAPI2.ApiModel.Converter.Settings);
    }

}
