// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ProxyAPI2.ApiModel;
//
//    var myResponse = MyResponse.FromJson(jsonString);

namespace ProxyAPI2.ApiModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MyResponse
    {
            public long id { get; set; }
            public string name { get; set; }
            public string username { get; set; }
            public string email { get; set; }
            public List<Post> posts { get; set; }

    }
}
