// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ProxyAPI2.ApiModel;
//
//    var post = Post.FromJson(jsonString);

namespace ProxyAPI2.ApiModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Post
    {
        [JsonProperty("userId")]
        public long UserId { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("comments")]
        public List<ApiModel.Comment> Comments { get; set; }


    }

    public partial class Post
    {
        public static Post[] FromJson(string json) => JsonConvert.DeserializeObject<Post[]>(json, ProxyAPI2.ApiModel.Converter.Settings);
    }

}
